import type { AdoRepoFile } from './adoGit';
import {
  buildPlaywrightHtmlReport, collectPlaywrightMediaAttachments, extractPlaywrightSpec,
  findLatestPlaywrightExecute,
} from './playwrightSpec';

export type AdoAttachment = {
  fileName: string;
  content: string;
  encoding?: 'utf8' | 'base64';
  comment?: string;
};

export type { AdoRepoFile };

function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null;
}

function looksLikeMarkdown(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (trimmed.startsWith('#') || trimmed.includes('\n## ')) return trimmed;
  return null;
}

export function collectAdoAttachments(opts: {
  upstream?: Record<string, unknown>;
  nodeOutputs?: Record<string, string>;
  testCases?: unknown[] | null;
  markdownReport?: string | null;
}): AdoAttachment[] {
  const attachments: AdoAttachment[] = [];
  const execute = opts.nodeOutputs ? findLatestPlaywrightExecute(opts.nodeOutputs) : null;
  const html = typeof execute?.htmlReport === 'string' && execute.htmlReport.trim()
    ? execute.htmlReport
    : execute
      ? buildPlaywrightHtmlReport(execute)
      : '';
  if (html.trim()) {
    attachments.push({
      fileName: 'playwright-report.html',
      content: html,
      comment: 'Playwright report with embedded screenshots and traces',
    });
  }
  attachments.push(...collectPlaywrightMediaAttachments(execute));

  if (opts.testCases?.length) {
    attachments.push({
      fileName: 'test-cases.json',
      content: JSON.stringify(opts.testCases, null, 2),
      comment: 'Generated test cases',
    });
  }

  let markdown = opts.markdownReport?.trim() || '';
  if (!markdown && opts.upstream) {
    for (const value of Object.values(opts.upstream)) {
      const rec = asRecord(value);
      const found = looksLikeMarkdown(value)
        ?? looksLikeMarkdown(rec?.report)
        ?? looksLikeMarkdown(rec?.result)
        ?? looksLikeMarkdown(rec?.markdown);
      if (found) {
        markdown = found;
        break;
      }
    }
  }
  if (markdown) {
    attachments.push({
      fileName: 'qe-report.md',
      content: markdown,
      comment: 'QE markdown report',
    });
  }

  return attachments;
}

export function collectAdoRepoFiles(opts: {
  upstream?: Record<string, unknown>;
  nodeOutputs?: Record<string, string>;
  sourceWorkItemId?: number | string | null;
}): AdoRepoFile[] {
  const execute = opts.nodeOutputs ? findLatestPlaywrightExecute(opts.nodeOutputs) : null;
  const spec = extractPlaywrightSpec('', {
    ...(opts.upstream ?? {}),
    ...(execute?.spec ? { spec: execute.spec } : {}),
  }) || (typeof execute?.spec === 'string' ? execute.spec : '');
  if (!spec.trim()) return [];
  const files: AdoRepoFile[] = [{
    path: 'generated.spec.ts',
    content: spec,
  }];
  if (opts.sourceWorkItemId != null && String(opts.sourceWorkItemId).trim()) {
    files.push({
      path: 'README.md',
      content: `# Generated Playwright spec\n\nSource work item: ${opts.sourceWorkItemId}\n\nGenerated by Agent Orchestration Studio.\n`,
    });
  }
  return files;
}
